### ISSUE TITLE
Fork and Hugo static website

### ISSUE THREAD

**Issue by dudung** [dudung/web-app-service-tasks#1]
Please put your ID and link to your Hugo static website below.

Example
+ `tid` 0000000
+ `url` https://rrkurnova.github.io/lecture-notes

Code to copy and paste
```
Example
+ `tid` 0000000
+ `url` https://rrkurnova.github.io/lecture-notes
```

**Comment by robinhuud15** [comment]
https://robinhuud15.github.io/lecture-notes/

**Comment by robinhuud15** [comment]
21181234
https://robinhuud15.github.io/lecture-notes/

**Comment by yunisangadji** [comment]
21181298
https://yunisangadji.github.io/lecture-notes/

**Comment by irhwam** [comment]
21181125

https://irhwam.github.io/lecture-notes/

**Comment by Kodhil** [comment]
https://Kodhil.github.io/lecture-notes/

**Comment by AKS4R4** [comment]
https://AKS4R4.github.io/lecture-notes
