### ISSUE TITLE
Medium story about how to scrap a Google SERP

### ISSUE THREAD

**Issue by dudung** [dudung/web-app-service-tasks#10]
+ Write you ID.
+ Give the link to your Medium story.

**Comment by yunisangadji** [comment]
Yulia Valonia 
NIT 21181298

https://medium.com/@yuniasangadji/apa-itu-web-sraping-fd48f4a6c876

**Comment by robinhuud15** [comment]
Robin Hudson
21181234

https://medium.com/@raflymaulana1508/apa-itu-web-scraping-641f245d4bfd

**Comment by MazamGanendra** [comment]
Mazam Ganendra
NIT 21181192

https://medium.com/@masjhurhusein/apa-itu-web-scraping-0d2d74c2c55b

**Comment by AKS4R4** [comment]
Rasha Muhammad
NIT 21181236

https://medium.com/@raihanmarlianto/pengalaman-mempelajari-dan-melakukan-scraping-google-66ebdb2c0bc5

**Comment by irhwam** [comment]
Irham Prajawiguna

21181125

https://medium.com/@prajawigoona/cara-mengikis-hasil-pencarian-google-scraping-2671790a50f1

**Comment by Kodhil** [comment]
21181092
https://medium.com/@arfansyahfadhilah/web-scraping-adalah-sebuah-cara-pengambilan-suatu-data-atau-informasi-tertentu-dengan-jumlah-besar-e8add474c6c8
