### ISSUE TITLE
Advance Google Search

### ISSUE THREAD

**Issue by dudung** [dudung/web-app-service-tasks#11]
Show how to find a definition about something in a particular website between 2000 and 2010.
+ Write your ID
+ Put the link here.
+ Show the results in the form of screenshots.

**Comment by yunisangadji** [comment]
21181298

https://www.google.com/search?q=define%3APapeda+site%3A+https%3A%2F%2Fid.wikipedia.org%2Fwiki%2FPapeda+after%3A2000+before%3A2010&sca_esv=575108319&sxsrf=AM9HkKlCbEIu1zDVktuVFZfIAXp6u9gc0w%3A1697786862350&ei=7isyZaiGFfmu4-EP0YS6yAc&ved=0ahUKEwiotdb2jISCAxV51zgGHVGCDnkQ4dUDCBE&uact=5&oq=define%3APapeda+site%3A+https%3A%2F%2Fid.wikipedia.org%2Fwiki%2FPapeda+after%3A2000+before%3A2010&gs_lp=Egxnd3Mtd2l6LXNlcnAiT2RlZmluZTpQYXBlZGEgc2l0ZTogaHR0cHM6Ly9pZC53aWtpcGVkaWEub3JnL3dpa2kvUGFwZWRhIGFmdGVyOjIwMDAgYmVmb3JlOjIwMTBI_LAGUJYFWOqmBnAKeAGQAQOYAdADoAGFFaoBCDIzLjUuNC0xuAEDyAEA-AEB-AECqAIRwgIKEAAYRxjWBBiwA8ICChAAGIoFGLADGEPCAg4QABjkAhjWBBiwA9gBAcICEBAuGIoFGMgDGLADGEPYAQLCAgcQIxiKBRgnwgINEC4YgwEYsQMYigUYQ8ICBBAAGAPCAgUQABiABMICCxAAGIAEGLEDGIMBwgIcEC4YgwEYsQMYigUYQxiXBRjcBBjeBBjfBNgBA8ICBxAjGOoCGCfCAhMQLhiKBRjIAxjqAhi0AhhD2AEC4gMEGAAgQYgGAZAGE7oGBggBEAEYCboGBggCEAEYCLoGBggDEAEYFA&sclient=gws-wiz-serp
![image](https://github.com/dudung/web-app-service-tasks/assets/145080762/bd3a00c7-46d9-4631-9b70-bdb3f4158b00)

**Comment by robinhuud15** [comment]
https://www.google.com/search?q=minuman+tradisional&oq=minum&gs_lcrp=EgZjaHJvbWUqDggAEEUYJxg7GIAEGIoFMg4IABBFGCcYOxiABBiKBTIGCAEQRRg5MgoIAhAuGLEDGIAEMgwIAxAjGCcYgAQYigUyDQgEEAAYsQMYyQMYgAQyBggFEEUYPDIGCAYQRRg8MgYIBxBFGDzSAQgzNzM2ajBqN6gCALACAA&sourceid=chrome&ie=UTF-8

![image](https://github.com/dudung/web-app-service-tasks/assets/144424835/0681b0c4-13e1-4068-be99-84ae09871aa1)

**Comment by AKS4R4** [comment]
https://github.com/dudung/lecture-notes/issues/17#issuecomment-1909256506

**Comment by AKS4R4** [comment]
https://www.google.com/search?q=define+%3A+baju+site+%3A+https%3A%2F%2Ftokopedia.com&sca_esv=601288450&sxsrf=ACQVn0-PQ8rAqqK-HNZR-d0RgtYByN1iiA%3A1706150837964&ei=tcuxZcu4Ov6-4-EPzp-J-Ac&ved=0ahUKEwiL54SVw_eDAxV-3zgGHc5PAn8Q4dUDCBA&uact=5&oq=define+%3A+baju+site+%3A+https%3A%2F%2Ftokopedia.com&gs_lp=Egxnd3Mtd2l6LXNlcnAiKmRlZmluZSA6IGJhanUgc2l0ZSA6IGh0dHBzOi8vdG9rb3BlZGlhLmNvbTIFECEYoAEyBRAhGKABSPh-UJQLWLBvcAl4AZABAJgBxwOgAZUwqgEKMC4yOC4yLjMuMrgBA8gBAPgBAcICChAAGEcY1gQYsAPCAggQABgWGB4YD8ICBhAAGBYYHsICCBAAGBYYHhgKwgILEAAYgAQYigUYhgPCAggQABiABBiiBMICBRAhGJ8FwgIHECEYChigAeIDBBgAIEGIBgGQBgg&sclient=gws-wiz-serp 
![image](https://github.com/dudung/web-app-service-tasks/assets/144425016/d52a0c32-3626-4489-985b-5c870df8bdab)

**Comment by irhwam** [comment]
21181125

https://www.google.com/search?q=define%3ABogor+site%3A+https%3A%2F%2Ftamansafari.com%2F&sca_esv=3c9560cf55c01e70&sxsrf=ACQVn08fFtLv0pK2FnFyD7Vs38D2OkQ3FQ%3A1706494624968&ei=oAq3ZdHYOoeGnesPyPmPkAQ&ved=0ahUKEwjRqLrvw4GEAxUHQ2cHHcj8A0IQ4dUDCBE&uact=5&oq=define%3ABogor+site%3A+https%3A%2F%2Ftamansafari.com%2F&gs_lp=Egxnd3Mtd2l6LXNlcnAiK2RlZmluZTpCb2dvciBzaXRlOiBodHRwczovL3RhbWFuc2FmYXJpLmNvbS9I5wRQ_wJY_wJwAXgAkAEAmAEvoAEvqgEBMbgBA8gBAPgBAcICBxAjGLADGCfiAwQYASBBiAYBkAYB&sclient=gws-wiz-serp

<img width="643" alt="Screenshot 2024-01-29 091149" src="https://github.com/dudung/web-app-service-tasks/assets/144425029/ef970004-5416-4d8c-bf03-eb28c88cb9bc">

**Comment by Kodhil** [comment]
21181092
https://www.google.com/search?q=define%3Awww.gibson.com&sca_esv=a25c15acbc52d6d7&sxsrf=ACQVn0-_blHvKFRZzyuxmSebsKLw6UixzA%3A1706503964476&ei=HC-3ZYvVHNyLnesPsaSfwA4&ved=0ahUKEwiL0_DU5oGEAxXcRWcHHTHSB-gQ4dUDCBE&oq=define%3Awww.gibson.com&gs_lp=Egxnd3Mtd2l6LXNlcnAiFWRlZmluZTp3d3cuZ2lic29uLmNvbUjsIlAAWNcRcAB4AZABAJgBV6ABngSqAQE4uAEMyAEA-AEB-AECwgIEECMYJ8ICChAjGIAEGIoFGCfCAhAQLhiABBiKBRhDGMcBGNEDwgIFEAAYgATCAgsQABiABBixAxiDAcICERAuGIAEGLEDGIMBGMcBGNEDwgIKEC4YgAQYigUYQ8ICChAAGIAEGIoFGEPCAggQABiABBixA8ICDhAuGIAEGIoFGLEDGIMBwgIIEAAYgAQYywHCAgoQABiABBjLARgK4gMEGAAgQQ&sclient=gws-wiz-serp
![Screenshot (307)](https://github.com/dudung/web-app-service-tasks/assets/144425101/611d47d8-270d-4c10-b5cc-9095271790d2)
