### ISSUE TITLE
Idea for a website and the result

### ISSUE THREAD

**Issue by dudung** [dudung/web-app-service-tasks#2]
+ Write your ID
+ Describe you idea in one paragraph in Indonesian language less than 100 words.
+ Link to the website.
+ Create a Hugo static website containing following components: LaTeX, Mermaid, ChartJS,   - Markdown for table, Markdown for YouTube video, Markdown for quote paragraph, Markdown for section and subsection, Markdown for external image, Markdown for link to external page, Pure HTML / JS / CSS, SVG image with animation.
+ Explain that the website has integrated meaning.

**Comment by yunisangadji** [comment]
21181298
saya membuat tips untuk pembuatan skripsi dengan baik dan benar

http://localhost:1313/lecture-notes/0047/

**Comment by irhwam** [comment]
21181125
Saya membuat artikel mengenai beruang laut

https://github.com/irhwam/lecture-notes/blob/8ac330de1119c0c6567cbe9b0d6b2a5849917929/sea_bears.md

**Comment by Kodhil** [comment]
21181092
SOEHARTO
https://github.com/Kodhil/lecture-notes/blob/main/README.md

**Comment by AKS4R4** [comment]
21181236
Saya membuat website yg menjelaskan tentang Amunisi pistol kaliber 9x19mm Parabellum dan beberapa Variasi nya
https://github.com/AKS4R4/lecture-notes/blob/main/README.md
