### ISSUE TITLE
Google SERP

### ISSUE THREAD

**Issue by dudung** [dudung/web-app-service-tasks#3]
Report a Google SERP from you search by writing
+ your ID
+ your Medium link, e.g. https://medium.com/@6unpnp
+ your GitHub profile page, e.g. https://github.com/dudung
+ your Google SERP, e.g. https://www.google.com/search?q=something

**Comment by Antara000** [comment]
- 21181161
- https://github.com/dudung/lecture-notes/issues/6#issuecomment-1772000688

**Comment by robinhuud15** [comment]
21181234
https://medium.com/@raflymaulana1508
https://github.com/robinhuud15
https://www.google.com/search?q=minuman+tradisional

**Comment by yunisangadji** [comment]
21181298

https://github.com/yunisangadji
https://medium.com/@yuniasangadji
https://www.google.com/search?q=papeda

**Comment by irhwam** [comment]
21181125

https://medium.com/@prajawigoona
https://github.com/irhwam
https://www.google.com/search?q=bogor

**Comment by AKS4R4** [comment]
21181236

https://medium.com/@raihanmarlianto
https://github.com/AKS4R4
https://www.google.com/search?q=9mmpistols

**Comment by Kodhil** [comment]
1.21181092
2.https://medium.com/@arfansyahfadhilah
3.https://github.com/Kodhil
4.https://www.google.com/search?q=jenis+jenis+senjata+tradisional
