### ISSUE TITLE
Screenshot of organic search elements and classes

### ISSUE THREAD

**Issue by dudung** [dudung/web-app-service-tasks#4]
+ Write you ID.
+ Paste screenshot of an organic search result of a Google SERP from you search, .e.g.
![image](https://github.com/dudung/lecture-notes/assets/7240685/f2141658-db22-4f8f-a9e4-5d7f646af657)

**Comment by Antara000** [comment]
- 21181161
- https://github.com/dudung/lecture-notes/issues/7#issuecomment-1772001415

**Comment by robinhuud15** [comment]
21181234
<img width="960" alt="ss web" src="https://github.com/dudung/web-app-service-tasks/assets/144424835/f91ab283-b970-42f0-bf05-f43dc4d72bf1">

**Comment by yunisangadji** [comment]
21181298

![image](https://github.com/dudung/web-app-service-tasks/assets/145080762/35774d4c-96fa-4316-a999-c851512e130b)

**Comment by irhwam** [comment]
21181125

<img width="960" alt="Screenshot 2023-10-20 101437" src="https://github.com/dudung/web-app-service-tasks/assets/144425029/ef755003-513d-4d9a-a8cc-11efb7ac5c63">

**Comment by AKS4R4** [comment]
![image](https://github.com/dudung/web-app-service-tasks/assets/144425016/ab315f0d-dadb-400f-ae90-26696e2cb762)

**Comment by Kodhil** [comment]
1.21181092
2.
![Screenshot (304)](https://github.com/dudung/web-app-service-tasks/assets/144425101/77f03c91-28e6-42a8-ab33-5adfd469f2e5)
