### ISSUE TITLE
Styles and elements for an organic result

### ISSUE THREAD

**Issue by dudung** [dudung/web-app-service-tasks#6]
Write from you SERP the styles and elements for an organic search result
+ Write you ID.
+ title, e.g. `LC20lb MBeuO DKV0Md > h3`
+ link
+ description
+ display link

**Comment by Antara000** [comment]
- 21181161
- https://github.com/dudung/lecture-notes/issues/9#issuecomment-1772224027

**Comment by yunisangadji** [comment]
21181298

Title : LC20lb MBeuO DKV0Md >h3
Link : qLRx3b >cite
Description : VwiC3b yXK7lf lyLwlc yDYNvb W8l4ac >span
Display Link : qLRx3b tjvcx GvPZzd cHaqb >cite

**Comment by robinhuud15** [comment]
21181234

Title : LC20Ib MBeuO DKV0md
Link : byrV5b
Description : VwiC3b yXK7lf lVm3ye r025kc hJNv6b Hdw6tb
Display Link : qLRx3b tjvcx GvPZzd cHaqb

**Comment by irhwam** [comment]
21181125

Title: LC20lb MBeuO DKV0Md
Link: MjjYud
Desc: VwiC3b yXK7lf lyLwlc yDYNvb W8l4ac lEBKkf
Display Link: tjvcx GvPZzd cHaqb

**Comment by AKS4R4** [comment]
21181236

Title : LC20lb MBeuO DKV0Md
Link : VuuXrf
Desc : VwiC3b yXK7lf lVm3ye r025kc hJNv6b Hdw6tb
Display Link : qLRx3b tjvcx GvPZzd cHaqb
