### ISSUE TITLE
GoogleorganicResultsScraper.js

### ISSUE THREAD

**Issue by dudung** [dudung/web-app-service-tasks#7]
+ Write you ID.
+ Download [`GoogleorganicResultsScraper.js`](https://github.com/Darshan972/GoogleScrapingBlogs/blob/main/GoogleorganicResultsScraper.js).
+ Execute it without modification.
+ Report the output here.

**Comment by Antara000** [comment]
- 21181161
- https://github.com/dudung/lecture-notes/issues/11#issuecomment-1772234199

**Comment by yunisangadji** [comment]
21181298

![Uploading image.png…]()

**Comment by yunisangadji** [comment]
21181298

![image](https://github.com/dudung/web-app-service-tasks/assets/145080762/7d015518-b950-48c9-9825-fb8207bc1b80)

**Comment by AKS4R4** [comment]
<img width="672" alt="276869123-8088fac5-0572-4489-8dde-17154f74ad8d" src="https://github.com/dudung/web-app-service-tasks/assets/144425016/0a1d0fa0-d7b7-4336-bd63-5772c7fbe8bd">

**Comment by robinhuud15** [comment]
21181234

<img width="605" alt="sbs" src="https://github.com/dudung/web-app-service-tasks/assets/144424835/07ec8da5-762e-49ee-8563-f2827e84f79e">

**Comment by Kodhil** [comment]
21181092
![Screenshot (305)](https://github.com/dudung/web-app-service-tasks/assets/144425101/af285a8b-2d5f-4569-b5ef-a020a01245ec)
