### ISSUE TITLE
Titles, links, snippets, displayed links of organic results using GoogleorganicResultsScraper.js

### ISSUE THREAD

**Issue by dudung** [dudung/web-app-service-tasks#8]
+ Write you ID.
+ Give lines of codes for obtaining titles, links, snippets, and displayed links of organic results. Only for lines.
+ Give the output showing that all information (titles, links, snippets, displayed links) are scraped from the SERP.

**Comment by Antara000** [comment]
- 21181161
- https://github.com/dudung/lecture-notes/issues/14#issuecomment-1772265312

**Comment by yunisangadji** [comment]
21181298

$(".LC20lb.MBeuO.DKV0Md").each((i, el) => {
titles[i] = $(el).text();
});
$(".VuuXrf").each((i, el) => {
links[i] = $(el).attr("href");
});
$(".VwiC3b.yXK7lf.lyLwlc.yDYNvb.W8l4ac").each((i, el) => {
snippets[i] = $(el).text();
});
$(".qLRx3b.tjvcx.GvPZzd.cHaqb").each((i, el) => {
displayedLinks[i] = $(el).text();
});

**Comment by AKS4R4** [comment]
21181236

$(".LC20lb.MBeuO.DKV0Md").each((i, el) => {
titles[i] = $(el).text();
});
$(".VuuXrf").each((i, el) => {
links[i] = $(el).attr("href");
});
$(".VwiC3b.yXK7lf.lVm3ye.r025kc.hJNv6b.Hdw6tb").each((i, el) => {
snippets[i] = $(el).text();
});
$(".qLRx3b.tjvcx.GvPZzd.cHaqb").each((i, el) => {
displayedLinks[i] = $(el).text();
});

**Comment by robinhuud15** [comment]
$(".LC20lb.MBeuO.DKV0Md").each((i, el) => {
titles[i] = $(el).text();
});
$(".VuuXrf").each((i, el) => {
links[i] = $(el).attr("href");
});
$(".VwiC3b.yXK7lf.lVm3ye.r025kc.hJNv6b.Hdw6tb").each((i, el) => {
snippets[i] = $(el).text();
});
$(".qLRx3b.tjvcx.GvPZzd.cHaqb").each((i, el) => {
displayedLinks[i] = $(el).text();
});

**Comment by irhwam** [comment]
21181125

$(".LC20lb.MBeuO.DKV0Md").each((i, el) => {
titles[i] = $(el).text();
});
$(".MjjYud").each((i, el) => {
links[i] = $(el).attr("href");
});
$(".VwiC3b.yXK7lf.lyLwlc.yDYNvb.W8l4ac.lEBKkf").each((i, el) => {
snippets[i] = $(el).text();
});
$(".tjvcx.GvPZzd.cHaqb").each((i, el) => {
displayedLinks[i] = $(el).text();
});

**Comment by Kodhil** [comment]
21181092
$(".LC20lb.MBeuO.DKV0Md").each((i, el) => {
titles[i] = $(el).text();
});
$(".MjjYud").each((i, el) => {
links[i] = $(el).attr("href");
});
$(".VwiC3b.yXK7lf.lyLwlc.yDYNvb.W8l4ac.lEBKkf").each((i, el) => {
snippets[i] = $(el).text();
});
$(".tjvcx.GvPZzd.cHaqb").each((i, el) => {
displayedLinks[i] = $(el).text();
});
