### ISSUE TITLE
Save JSON file for organic results from Google SERP

### ISSUE THREAD

**Issue by dudung** [dudung/web-app-service-tasks#9]
+ Write you ID.
+ Write additional lines of codes for saving organic results from SERP in a JSON file.
+ Screenshot content of the JSON file.

**Comment by yunisangadji** [comment]
21181298

const fs = memerlukan("fs");
// Simpan hasil organik ke file JSON
const jsonData = JSON.stringify(organicResults, null, 2);
fs.writeFileSync("organic_results.json", jsonData);
});
};


![image](https://github.com/dudung/web-app-service-tasks/assets/145080762/39be78ce-0262-469f-a87b-adfbd00e0bd6)

**Comment by robinhuud15** [comment]
const fs = memerlukan("fs");
// Simpan hasil organik ke file JSON
const jsonData = JSON.stringify(organicResults, null, 2);
fs.writeFileSync("organic_results.json", jsonData);
});
};

**Comment by Kodhil** [comment]
21181092
const fs = memerlukan("fs");
// Simpan hasil organik ke file JSON
const jsonData = JSON.stringify(organicResults, null, 2);
fs.writeFileSync("organic_results.json", jsonData);
});
};
![299387452-39be78ce-0262-469f-a87b-adfbd00e0bd6](https://github.com/dudung/web-app-service-tasks/assets/144425101/f39da02c-5c11-48e9-91a8-eee1cb56d180)

**Comment by AKS4R4** [comment]
21181092
const fs = memerlukan("fs");
// Simpan hasil organik ke file JSON
const jsonData = JSON.stringify(organicResults, null, 2);
fs.writeFileSync("organic_results.json", jsonData);
});
};
![image](https://github.com/dudung/web-app-service-tasks/assets/144425016/17a5c4d3-4a44-4df1-b916-b660c9a1d0de)
